name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker Image
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/ai-gift-app:latest .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/ai-gift-app:latest

    - name: Deploy Azure Container Instance
      run: |
        az container show \
          --resource-group giftrecommender-2025_ai-rg \
          --name ai-gift-app > /dev/null 2>&1 && \
        (az container delete \
          --resource-group giftrecommender-2025_ai-rg \
          --name ai-gift-app --yes && \
        echo "Deleted existing container.") || \
        echo "No container found. Proceeding to create a new one."
        
        az container create \
          --resource-group giftrecommender-2025_ai-rg \
          --name ai-gift-app \
          --image ${{ secrets.ACR_LOGIN_SERVER }}/ai-gift-app:latest \
          --os-type Linux \
          --cpu 1 \
          --memory 1 \
          --ports 5001 \
          --ip-address Public \
          --environment-variables OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }}
